import type { Locale } from "./common";

export const consumerRoutes = {
  login: (locale: Locale) => `/${locale}/auth/sign-in`,
  signup: (locale: Locale) => `/${locale}/auth/sign-up`,
  forgotPassword: (locale: Locale) => `/${locale}/auth/reset-password`,
  app: (locale: Locale) => `/${locale}/home`,
  terms: (locale: Locale) => `/${locale}/terms`,
  announcements: (locale: Locale) => `/${locale}/announcements`,
  onboarding: (locale: Locale) => `/${locale}/onboarding`,
  library: (locale: Locale) => `/${locale}/library`,
  stats: (locale: Locale) => `/${locale}/stats`,
  calendar: (locale: Locale) => `/${locale}/calendar`,
  account: (locale: Locale) => `/${locale}/account`,
  bookList: (locale: Locale) => `/${locale}/book-list`,
  newBook: (locale: Locale) => `/${locale}/books/new`,
  book: (locale: Locale, bookId: string) => `/${locale}/books/${bookId}`,
  reading: (locale: Locale, bookId: string) => `/${locale}/reading/${bookId}`,
  recall: (locale: Locale) => `/${locale}/library?mode=recall`,
  review: (locale: Locale, bookId: string) => `/${locale}/books/${bookId}/review`,
  mindMap: (locale: Locale, bookId: string) => `/${locale}/books/${bookId}/mind-map`,
  scan: (locale: Locale) => `/${locale}/books/scan`,
  subscription: (locale: Locale) => `/${locale}/subscription`,
  privacy: (locale: Locale) => `/${locale}/privacy`,
  authCallback: "/auth/callback",
  authResetPassword: "/auth/reset-password",
} as const;
